### ISSUE TITLE
Serverfehler  500

### ISSUE THREAD

**Issue by Kalle801** [agrafix/managerslife#1]
Hallo.

Erstmal Danke für das Game ;)

Ich habe es installiert und es funktioniert soweit. Nur nach dem Login kommt ein serverfehler:

Serverfehler 500
http://social-prank.com/game/index

Gibt es dafür vielleicht eine lösung, oder habe ich etwas vergessen?

Liebe Grüße.

Email: kalle801@gmail.com

**Comment by agrafix** [comment]
Kannst du deine Error-Logs posten?

**Comment by Kalle801** [comment]
[Thu Feb 04 01:33:12 2016] [error] [client 108.162.246.206] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 02:45:42 2016] [error] [client 173.245.55.246] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/, referer: http://www.bing.com
[Thu Feb 04 03:19:10 2016] [error] [client 108.162.222.53] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 03:19:22 2016] [error] [client 108.162.222.53] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 04:18:51 2016] [error] [client 108.162.222.53] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 04:19:03 2016] [error] [client 108.162.222.53] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 06:36:21 2016] [error] [client 108.162.208.57] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 06:36:22 2016] [error] [client 108.162.208.57] File does not exist: /data/www/b4/1393/html/social-prank.com/administrator
[Thu Feb 04 07:32:58 2016] [error] [client 108.162.246.205] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 09:17:41 2016] [error] [client 108.162.246.211] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 09:42:11 2016] [error] [client 173.245.54.250] File does not exist: /data/www/b4/1393/html/social-prank.com/robots.txt
[Thu Feb 04 09:42:13 2016] [error] [client 173.245.54.253] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 12:04:31 2016] [error] [client 173.245.55.214] File does not exist: /data/www/b4/1393/html/social-prank.com/robots.txt
[Thu Feb 04 12:04:32 2016] [error] [client 108.162.216.247] File does not exist: /data/www/b4/1393/html/social-prank.com/m
[Thu Feb 04 12:17:56 2016] [error] [client 108.162.222.53] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 12:18:06 2016] [error] [client 108.162.222.53] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 13:02:19 2016] [error] [client 173.245.53.192] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 15:50:45 2016] [error] [client 108.162.216.240] File does not exist: /data/www/b4/1393/html/social-prank.com/robots.txt
[Thu Feb 04 15:50:45 2016] [error] [client 108.162.216.239] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 18:17:10 2016] [error] [client 108.162.222.53] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 18:17:17 2016] [error] [client 108.162.222.53] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 19:22:17 2016] [error] [client 108.162.246.246] File does not exist: /data/www/b4/1393/html/social-prank.com/robots.txt
[Thu Feb 04 19:22:34 2016] [error] [client 108.162.246.205] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 19:48:07 2016] [error] [client 173.245.55.234] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 19:48:07 2016] [error] [client 173.245.49.248] File does not exist: /data/www/b4/1393/html/social-prank.com/robots.txt
[Thu Feb 04 19:48:13 2016] [error] [client 108.162.229.72] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 19:48:17 2016] [error] [client 108.162.229.72] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 19:48:18 2016] [error] [client 108.162.229.72] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 20:06:42 2016] [error] [client 108.162.216.240] File does not exist: /data/www/b4/1393/html/social-prank.com/robots.txt
[Thu Feb 04 20:06:44 2016] [error] [client 108.162.216.234] File does not exist: /data/www/b4/1393/html/social-prank.com/change_log.html
[Thu Feb 04 20:13:45 2016] [error] [client 108.162.212.209] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/, referer: http://top1-seo-service.com/try.php?u=http://social-prank.com
[Thu Feb 04 21:15:20 2016] [error] [client 108.162.222.53] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 21:15:24 2016] [error] [client 108.162.222.53] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/
[Thu Feb 04 22:31:09 2016] [error] [client 108.162.222.41] File does not exist: /data/www/b4/1393/html/social-prank.com/robots.txt
[Thu Feb 04 23:09:08 2016] [error] [client 108.162.212.252] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/, referer: http://top1-seo-service.com/try.php?u=http://social-prank.com
[Fri Feb 05 01:14:13 2016] [error] [client 108.162.246.225] File does not exist: /data/www/b4/1393/html/social-prank.com/robots.txt
[Fri Feb 05 01:14:18 2016] [error] [client 108.162.246.206] Directory index forbidden by Options directive: /data/www/b4/1393/html/social-prank.com/

**Comment by agrafix** [comment]
Wo ist denn da der 500 Fehler? Ich sehe nur forbidden und does not exist.

**Comment by Kalle801** [comment]
Der fehler ist nur zusehen wenn man sich einloggt. Gleich nach der weiterleitung.

Beim Abrufen von http://social-prank.com/game/index ist auf der Website ein Fehler aufgetreten. Möglicherweise wird sie gerade gewartet oder ist falsch konfiguriert.

**Comment by agrafix** [comment]
Vielleicht wird die .htaccess Datei (siehe https://github.com/agrafix/managerslife/blob/d0d5ddb037ccd77ab0441355c272c5a3493b111f/.htaccess ) nicht richtig verarbeitet? Ist das ein Rootserver?

**Comment by Kalle801** [comment]
Hm nein, die htaccess lines sind die selben wie in deinem Link. Ich nutze ein shared hosting Account.

**Comment by agrafix** [comment]
Vielleicht ist bei deinem shared hosting ModRewrite deaktiviert/aus.

**Comment by Kalle801** [comment]
nein es ist an :)

**Comment by agrafix** [comment]
Dann musst du in den ErrorLog von Apache schauen um zu sehen was genau schief geht. Vielleicht ist's ja auch ein PHP Fehler der verschluckt wird.

**Comment by Kalle801** [comment]
Das kann sein. Ich werde das script später mal auf nem Vserver testen.

Oder ist es mit xampp auch lauffähig, dann sehe ich dort nach.

**Comment by Kalle801** [comment]
Bei Xampp kommt folgendes:

Notice: Trying to get property of non-object in C:\xampp\htdocs\models\Model_Quests_npc.class.php on line 15

Fatal error: Call to a member function getID() on string in C:\xampp\htdocs\models\Model_Quests_npc.class.php on line 17

Ps: Ich bin mal eben essen machen und melde mich wieder.

**Comment by agrafix** [comment]
Ah, sieht so aus als ob die NPCs auf der Karte fehlen

**Comment by agrafix** [comment]
Musst vermutlich noch `prepare.sql` in MySQL einspielen

**Comment by Kalle801** [comment]
okay, aber wo finde ich die? :D

**Comment by agrafix** [comment]
Im repository

**Comment by Kalle801** [comment]
repository finde ich ebenfalls nicht.
Im moment sieht es in der datenbank so aus:
http://img5.fotos-hochladen.net/uploads/unbenanntgxurtmie43.png

ps: es gibt nur die schema.sql

Edit: Habe deinen nachtrag gefuden "prepare.sql" jetzt funktioniert es :)

Besten Dank!

**Comment by agrafix** [comment]
Super! Vergiss nicht den Cronjob einzurichten :-)

**Comment by Kalle801** [comment]
Ich sehe gerade: Nach klick auf einen npc läd es in einer unendlich-schleife.
